# Generated by Django 6.0.1 on 2026-02-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID number for primary identification', max_length=20, null=True, unique=True),
        ),
    ]
