# Generated by Django 6.0.1 on 2026-02-17 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g. v1.0, v1.1', max_length=20, unique=True)),
                ('accuracy', models.FloatField(help_text='Test accuracy 0.0 - 1.0')),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(help_text='Number of samples used for training')),
                ('test_samples', models.IntegerField(default=0)),
                ('num_classes', models.IntegerField(default=0, help_text='Number of disease classes')),
                ('feature_count', models.IntegerField(default=0, help_text='Number of features used')),
                ('model_file', models.CharField(help_text='Path to serialized model file', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Currently active model')),
                ('notes', models.TextField(blank=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Model Version',
                'verbose_name_plural': 'ML Model Versions',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_input', models.TextField()),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=10)),
                ('prediction_1', models.CharField(max_length=200)),
                ('confidence_1', models.FloatField()),
                ('prediction_2', models.CharField(blank=True, max_length=200)),
                ('confidence_2', models.FloatField(blank=True, null=True)),
                ('prediction_3', models.CharField(blank=True, max_length=200)),
                ('confidence_3', models.FloatField(blank=True, null=True)),
                ('feedback_received', models.BooleanField(default=False, help_text='Whether doctor confirmed/corrected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_services.mlmodelversion')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('predicted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Body temperature in Celsius', null=True)),
                ('spo2', models.IntegerField(blank=True, help_text='Oxygen saturation %', null=True)),
                ('symptoms', models.TextField(help_text='Comma-separated symptom keywords')),
                ('predicted_disease', models.CharField(blank=True, help_text='What the ML model predicted', max_length=200)),
                ('predicted_confidence', models.FloatField(blank=True, null=True)),
                ('confirmed_disease', models.CharField(help_text="Doctor's confirmed/corrected diagnosis", max_length=200)),
                ('icd_code', models.CharField(blank=True, help_text='ICD-10 code', max_length=20)),
                ('prediction_correct', models.BooleanField(default=False)),
                ('used_for_training', models.BooleanField(default=False, help_text='Whether this record has been used in training')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_confirmations', to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(blank=True, help_text='Model version used for prediction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_services.mlmodelversion')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Data',
                'verbose_name_plural': 'Training Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
