# Generated by Django 6.0.1 on 2026-02-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodelversion',
            name='class_labels',
            field=models.TextField(blank=True, help_text='JSON: class label names'),
        ),
        migrations.AddField(
            model_name='mlmodelversion',
            name='confusion_matrix',
            field=models.TextField(blank=True, help_text='JSON: confusion matrix'),
        ),
        migrations.AddField(
            model_name='mlmodelversion',
            name='feature_importances',
            field=models.TextField(blank=True, help_text='JSON: feature importance scores'),
        ),
        migrations.AddField(
            model_name='mlmodelversion',
            name='per_class_metrics',
            field=models.TextField(blank=True, help_text='JSON: per-class P/R/F1'),
        ),
    ]
